# Generated by Django 5.0.6 on 2024-12-07 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('first_name', models.CharField(max_length=20)),
                ('symptoms', models.CharField(max_length=200)),
            ],
        ),
    ]
